version: "3"
services:

  db:
    container_name: db
    image: docker.io/postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  alice:
    container_name: alice
    image: docker.io/bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5
    ports:
      - "3001:3001"
    environment:
      - RUST_LOG=TRACE
    command: >
      start -it http 0.0.0.0 3000
        --label Alice
        -ot http
        -e http://alice:3000
        --admin 0.0.0.0 3001 --admin-insecure-mode
        --log-level debug
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --tails-server-base-url http://tails:6543
        --wallet-type askar
        --wallet-name alice
        --wallet-key alice_insecure0
        --wallet-storage-type postgres_storage
        --wallet-storage-config '{"url":"db:5432","max_connections":5}'
        --wallet-storage-creds '{"account":"postgres","password":"mysecretpassword","admin_account":"postgres","admin_password":"mysecretpassword"}'
        --preserve-exchange-records
        --auto-provision
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started
      db:
        condition: service_healthy

  bob:
    container_name: bob
    image: docker.io/bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5
    ports:
      - "3002:3001"
    command: >
      start -it http 0.0.0.0 3000
        --label Bob
        -ot http
        -e http://bob:3000
        --admin 0.0.0.0 3001 --admin-insecure-mode
        --log-level debug
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --tails-server-base-url http://tails:6543
        --wallet-type askar
        --wallet-name bob
        --wallet-key bob_insecure0
        --wallet-storage-type postgres_storage
        --wallet-storage-config '{"url":"db:5432","max_connections":5}'
        --wallet-storage-creds '{"account":"postgres","password":"mysecretpassword","admin_account":"postgres","admin_password":"mysecretpassword"}'
        --preserve-exchange-records
        --auto-provision
        --monitor-revocation-notification
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started
      db:
        condition: service_healthy
  tails:
    image: ghcr.io/bcgov/tails-server:latest
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO

